# Generated by Django 4.1.3 on 2022-11-09 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_task__api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
